# **Libraries in Python**

**Numpy**

In [ ]:
my_list=[1,2,3,4]

In [ ]:
import numpy as np

# **Cast into Array**

In [ ]:
np.array(my_list)

array([1, 2, 3, 4])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
type(arr)

numpy.ndarray

# **Check Number of Dimensions**

In [ ]:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

NameError: name 'np' is not defined

**NumPy Array Indexing**

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])



1
3
4
5


**Get even NUmbers**

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Diagonal Matrix get by eye attribut**

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Array Slicing**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(f"positive slicing :",arr[1:5])
#negative slicing
print(f"Nagtive slicing :",arr[-3:-1])

positive slicing : [2 3 4 5]
Nagtive slicing : [4 5]


**Data Type of array**

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([1,2,3],dtype='S')
arr3=np.array([1.1,2.0,3.2])
arr4=np.array(['sandy','Mahesh','Nagesh'])
arr5=np.array([1,2,3])
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)
print(arr5.dtype)


int64
|S1
float64
<U6
int64


Array with Array

In [ ]:
import numpy as np

In [ ]:
arr =np.arange(0,10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [ ]:
arr*2-100

array([-100,  -98,  -96,  -94,  -92,  -90,  -88,  -86,  -84,  -82])

Copy dot array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


**Copy and view**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()
print(x)
print(x.base)
print(y.base)

[1 2 3 4 5]
None
[1 2 3 4 5]


**Shape**=

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

**Resize** **Array**/**shape**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)



[1 2 3 4 5 6 7 8]


**Join** **Array**

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


**With** **Stack** **Function**

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


**Array_Spliting**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


**Split the array in 4 parts**

In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5]


**Split 2 -D array**

In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


***Find the postion of values***
# With the help of **Where** Method

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
y= np.where(arr==1)

print(x)
print(y)

(array([3, 5, 6]),)
(array([0]),)


**Find the index of even Number **

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)
Y = np.where(arr%2 == 1)

print(x)
print(Y)

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


**Search Sorted**
side will be selected by
**Side='left/right '**

In [ ]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7,side='right')

print("Index no: ",x)

Index no:  2


**Find the indexes where the values 2, 4, and 6 should be inserted:**

In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 8])

print(x)

[1 2 4]


In [ ]:
from numpy import random
x=random.randint(10)
print(x)

5


In [ ]:
from numpy import random

x = random.rand()

print(x)

0.9207604978179763


 **Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):**

In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)